language:
  - cpp
compiler:
  - gcc
  - clang
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install libgtk-3-dev qtbase5-dev qtmultimedia5-dev
  - sudo apt-get install libasound2-dev libavformat-dev libbinio-dev libbs2b-dev
  - sudo apt-get install libcddb2-dev libcdio-cdda-dev libcue-dev libcurl4-gnutls-dev
  - sudo apt-get install libdbus-glib-1-dev libfaad-dev libflac-dev libfluidsynth-dev
  - sudo apt-get install libgl1-mesa-dev libjack-jackd2-dev liblircclient-dev
  - sudo apt-get install libmms-dev libmodplug-dev libmp3lame-dev libmpg123-dev
  - sudo apt-get install libneon27-gnutls-dev libnotify-dev libpulse-dev
  - sudo apt-get install libsamplerate0-dev libsdl1.2-dev libsidplayfp-dev
  - sudo apt-get install libsndfile1-dev libsoxr-dev libvorbis-dev libwavpack-dev
  - sudo apt-get install libxml2-dev libadplug-dev
install:
  - git clone git://github.com/audacious-media-player/audacious.git audacious
  - git checkout master-gtk3
  - cd audacious
  - ./autogen.sh
  - ./configure --prefix=/opt/aud --enable-qt
  - make
  - sudo make install
  - cd ..
script:
  - export PKG_CONFIG_PATH=/opt/aud/lib/pkgconfig
  - ./autogen.sh
  - ./configure --prefix=/opt/aud --enable-qt
  - make
