name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    strategy:
      matrix:
        os: ['ubuntu-20.04', 'ubuntu-22.04', 'macos-12', 'windows-2022']
        build-system: ['autotools', 'meson']
      fail-fast: false
    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout audacious-plugins
      uses: actions/checkout@v3

    - name: Checkout audacious
      uses: actions/checkout@v3
      with:
        repository: audacious-media-player/audacious
        path: audacious

    - name: Install dependencies
      uses: ./.github/actions/install-dependencies
      with:
        os: ${{ matrix.os }}
        build-system: ${{ matrix.build-system }}

    - name: Configure audacious
      uses: ./audacious/.github/actions/run-action
      with:
        action: 'configure'
        os: ${{ matrix.os }}
        build-system: ${{ matrix.build-system }}

    - name: Build audacious
      uses: ./audacious/.github/actions/run-action
      with:
        action: 'build'
        os: ${{ matrix.os }}
        build-system: ${{ matrix.build-system }}

    - name: Install audacious
      uses: ./audacious/.github/actions/run-action
      with:
        action: 'install'
        os: ${{ matrix.os }}
        build-system: ${{ matrix.build-system }}

    - name: Configure audacious-plugins
      uses: ./.github/actions/run-action
      with:
        action: 'configure'
        os: ${{ matrix.os }}
        build-system: ${{ matrix.build-system }}

    - name: Build audacious-plugins
      uses: ./.github/actions/run-action
      with:
        action: 'build'
        os: ${{ matrix.os }}
        build-system: ${{ matrix.build-system }}

    - name: Install audacious-plugins
      uses: ./.github/actions/run-action
      with:
        action: 'install'
        os: ${{ matrix.os }}
        build-system: ${{ matrix.build-system }}
